### ISSUE TITLE
Filename inside Archive possible bug

### ISSUE THREAD

**Issue by Roxyrob** [MailScanner/v5#19]
Found possible bug in the Filename Check inside Archive.

Software versions:
   MailScanner Version:4.84.6   
   MailWatch Version:1.2.0 - RC2
   ClamAV Version:0.99.2 
   SpamAssassin Version:3.3.1 

I use config with these deny:
   Filename Deny \..*exe$ ...
   Archive Filename Deny \..*exe$ ...

You can reproduce the behavior doing so:

1. Crate a dummy c.exe file
2. Compress c.exe in a c.zip
3. Compress c.zip in a c1.zip
4. Compress c1.zip in a c2.zip

Send a test mail with all 4 files in attach: c.exe c.zip c1.zip c2.zip

c.exe OK: is correctly blocked by Filename Deny (warning is send with alert on c.exe blocket)
c.zip OK: is correctly blocked by Filename Deny in Archive (BUG: no warning is sent for this attach, as file disappears)
c1.zip BUG: erroneously is not blocked so attach passed check (naturally no warning)
c2.zip OK: is correctly blocked by Filename Deny (warning is send with alert on c.exe inside)

So one file seams disappeared and one file is not blocked..

This is MailScanner Log part:

MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED c1.zip
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED c.zip
MailScanner[15060]: Filename Checks: Windows/DOS Executable (D72E62205D.AAFED c.exe)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED core.xml (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED sheet1.xml (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED workbook.xml (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED theme1.xml (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED styles.xml (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED workbook.xml.rels (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED 0000.dat (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED app.xml (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED .rels (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED Content_Types.xml (no rule matched)
MailScanner[15060]: Filename Checks: Blocked Filename Detected (D72E62205D.AAFED c.exe)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED c.zip
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED c1.zip
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED c2.zip
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED msg-15060-2.html (no rule matched)
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED msg-15060-1.txt
MailScanner[15060]: Other Checks: Found 2 problems
MailScanner[15060]: Virus and Content Scanning: Starting
MailScanner[15060]: Virus Scanning completed at 4074 bytes per second
MailScanner[15060]: Saved entire message to ...
MailScanner[15060]: Saved infected "c.zip" to ...
MailScanner[15060]: Saved infected "c.exe" to ...
MailScanner[15060]: Saved infected "c.exe" to ...
MailScanner[15060]: Spam Checks: Starting
MailScanner[15060]: Delivery of nonspam: message D72E62205D.AAFED from ... to ... with subject ...
MailScanner[15060]: Spam Checks completed at 18008 bytes per second
MailScanner[15060]: Requeue: D72E62205D.AAFED to BCB3123ECD
MailScanner[15060]: Cleaned: Delivered 1 cleaned messages
MailScanner[15060]: Virus Processing completed at 344764 bytes per second
MailScanner[15060]: Deleted 1 messages from processing-database
MailScanner[15060]: Batch completed at 3288 bytes per second (34353 / 10)
MailScanner[15060]: Batch (1 message) processed in 10.45 seconds

Regards

**Comment by shawniverson** [comment]
What's your Maximum Archive Depth?

**Comment by msapiro** [comment]
I have tried your test with just a brief message and the 4 attached files. It works for me.

I think this is the issue fixed by https://github.com/MailScanner/v4/commit/9a07a5196005f7d832c29d9ee6636beed6d47c70 which fix was actually first release with the initial https://github.com/MailScanner/v5 release.

If that patch doesn't fix this, you can reopen this issue.

**Comment by Roxyrob** [comment]
Maximum Archive Depth = 8
I have to test with version 5, but I use Mailscanner on Centos 6 with epel repo not a compiled version at least as now... As soon as possible I'll test the patch

**Comment by Roxyrob** [comment]
Someone can point me to the correct path to upgrade mailscanner on Centos 6 using rpm ? I have to avoid trouble as much as possible (system is in production...),

**Comment by Roxyrob** [comment]
The patch  MailScanner/v4@9a07a51 per se does not solve the issue

**Comment by msapiro** [comment]
Did you restart MailScanner between applying the patch and testing? If so, what are the relevant log messages? Mine are
```
Sep 25 11:25:46 msapiro MailScanner[2837]: Filename Checks: Windows/DOS Executable (BDF273402DB.A8F3E c.exe)
Sep 25 11:25:46 msapiro MailScanner[2837]: message repeated 3 times: [ Filename Checks: Windows/DOS Executable (BDF273402DB.A8F3E c.exe)]
Sep 25 11:25:46 msapiro MailScanner[2837]: Other Checks: Found 4 problems
Sep 25 11:25:46 msapiro MailScanner[2837]: Virus and Content Scanning: Starting
Sep 25 11:25:46 msapiro MailScanner[2837]: Saved entire message to /var/spool/MailScanner/quarantine/20160925/BDF273402DB.A8F3E
Sep 25 11:25:46 msapiro MailScanner[2837]: Saved infected "c.exe" to /var/spool/MailScanner/quarantine/20160925/BDF273402DB.A8F3E
Sep 25 11:25:46 msapiro MailScanner[2837]: Saved infected "5c.exe" to /var/spool/MailScanner/quarantine/20160925/BDF273402DB.A8F3E
Sep 25 11:25:46 msapiro MailScanner[2837]: Saved infected "6c.exe" to /var/spool/MailScanner/quarantine/20160925/BDF273402DB.A8F3E
Sep 25 11:25:46 msapiro MailScanner[2837]: Saved infected "c.zip" to /var/spool/MailScannerquarantine/20160925/BDF273402DB.A8F3E
Sep 25 11:25:46 msapiro MailScanner[2837]: Saved infected "1c.zip" to /var/spool/MailScannerquarantine/20160925/BDF273402DB.A8F3E
Sep 25 11:25:46 msapiro MailScanner[2837]: Saved infected "3c.exe" to /var/spool/MailScannerquarantine/20160925/BDF273402DB.A8F3E
Sep 25 11:25:46 msapiro MailScanner[2837]: Saved infected "4c.zip" to /var/spool/MailScannerquarantine/20160925/BDF273402DB.A8F3E
```
The digits preceding the file names are the important thing.

I do note that your log messages include
```
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED c.zip
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED c1.zip
MailScanner[15060]: Filename Checks: Allowing D72E62205D.AAFED c2.zip
```
and your message has more parts than the simple message described at "You can reproduce the behavior doing so:". Does your patched Mailscanner fail on a simple text/plain message with just the four attached files?
